### ISSUE TITLE
Database - Full text search fails

### ISSUE THREAD

**Issue by Nazeh** [Telios-org/nebula#1]
`q1.length` and  `q2.length` are both Zero

**Comment by hexadecible** [comment]
It appears Hyperbee v1.8.0 broke search. I'll be working on upgrading all Hyper modules to the latest, but for now, I need to lock them down to specific versions to avoid the alpha breaking changes. #819d7a7

**Comment by hexadecible** [comment]
Fixed in v2.5.6
